default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: ouchi_note_development

test:
  <<: *default
  database: ouchi_note_test

production:
  <<: *default
  database: ouchi_note_production
  url: <%= ENV['DATABASE_URL'] %>